language: python
python: 2.7
env:
  global:
  - secure: uCajy1mT1Rk5vzco8hkuRTU+0QlFg1crOyw71bMkTzgzz32Pr+B8F0GOjjxcOB0ZQzpQoVzemBasskOCEejWzJvR7Hm+MO2WDcGX9HrjdPT7SeRpWldxDKU+tBADvCZXcIMiff1fZbPc+BCpwmZPTT3goAZD9dPvNqnzh0pzO3M=
  matrix:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pypy
script:
	- tox -e $TOX_ENV
install:
	- pip install tox
